name: "Post to Bluesky"

on:
  workflow_dispatch:
#  schedule:
#    - cron: "*/5 * * * *" # co 5 minut

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pobierz poprzedni .lastTweet (jeśli istnieje)
        uses: actions/download-artifact@v4
        with:
          name: lastTweet
          path: .
        continue-on-error: true

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - run: npm ci
      - run: npm run build

      - name: Send post
        run: npm start
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}

      - name: Zapisz nowy .lastTweet jako artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: lastTweet
          path: .lastTweet
          if-no-files-found: ignore
