name: Post

on:
  schedule:
  #  cron: "*/30 * * * *" # co 5 minut
  workflow_dispatch: # umożliwia ręczne uruchomienie

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Przywróć cache .lastTweet
        uses: actions/cache@v4
        with:
          path: .lastTweet
          key: lastTweet-cache
          restore-keys: lastTweet-cache

      - name: Utwórz plik .lastTweet, jeśli nie istnieje
        run: |
          if [ ! -f .lastTweet ]; then
            echo "0" > .lastTweet
          fi

      - name: Ustaw Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instaluj zależności
        run: npm ci

      - name: Uruchom bota
        run: node index.js

      - name: Zaktualizuj cache .lastTweet
        uses: actions/cache@v4
        with:
          path: .lastTweet
          key: lastTweet-cache-${{ hashFiles('.lastTweet') }}
          restore-keys: lastTweet-cache
