jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Przywróć cache .lastTweet
        uses: actions/cache@v4
        with:
          path: .lastTweet
          key: lastTweet-cache
          restore-keys: |
            lastTweet-cache

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - run: npm ci
      - run: npm run build

      - name: Send post
        run: npm start
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}

      - name: Zaktualizuj cache .lastTweet
        uses: actions/cache@v4
        with:
          path: .lastTweet
          key: lastTweet-cache-${{ github.run_id }}
          restore-keys: |
            lastTweet-cache
