name: "𝕏 📨 🦋"

on:
  workflow_dispatch:
#  schedule:
#    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Ustaw Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - run: npm ci
      - run: npm run build

      - name: Uruchom bota
        run: npm start
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}

      - name: Commit pliku .lastTweet (jeśli zmieniony)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .lastTweet || true
          git diff --cached --quiet || git commit -m "🤖 Update .lastTweet"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
